import Head from 'next/head'
import { HeadBar } from '../components/headBar'
import { UserProvider } from '../context/UserProvider'
import { TaskListProvider } from '../context/TasksListProvider'
import { MainLayout } from '../components/MainLayout'
import { ThemeProvider } from '@mui/system'
import { theme } from '../styles/MUI/themes'
import { Box } from '@mui/material'

export default function Home() {

  return (
    <Box sx={{  minWidth: '360px' }}>
      <Head>
        <title>Rapid Task</title>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <UserProvider>
          <HeadBar />
          <TaskListProvider>
            <MainLayout />
          </TaskListProvider>
        </UserProvider>
      </ThemeProvider>
    </Box >
  )
}
